### ISSUE TITLE
[FEAT] 기본 response 설정

### ISSUE THREAD

**Issue by sueelly** [f-lab-edu/SnapNOW#1]
# Contents
response에 사용되는 기본 설정을 완료한다.

## Description
snapnow-core 모듈 (공통 모듈)에 response에 필요한 클래스들을 구현한다.

## Todo

-   [ ] ApiResponse: 공통 반환 Dto. ResultCode와 message, data, page를 갖는다.
-   [ ] SnapnowException: RuntimeException을 상속받는 custom exception class. ResultCode를 필드로 갖는다.
-   [ ] 이외 Exception classes(BadRequestException etc): SnapnowException을 상속받는 custom exception class들을 구현한다. 보편적으로 많이 쓰이는 BadRequestException, IllegalArgumentException 등을 구현한다. 추후 기능 구현 시 이 클래스들을 상속받아 보다 명확하게 예외를 처리한다.
-   [ ] ResultCode: ApiResponse에서 쓰는 result code.... 원래는 enum으로 하는데 그러면 모든 예외 enum을 이곳에 정의해야해서 상속받을 수 있는 interface로 구현하자...

## Check Priority

Expected Priority: MEDIUM

## Reference (Optional)

(null)
