### ISSUE TITLE
[FEAT] File Domain

### ISSUE THREAD

**Issue by sueelly** [f-lab-edu/SnapNOW#10]
# Contents

File Domain 클래스들을 구현한다.

## Description

File Domain 모듈에서 하는 일은 다음과 같다.
- user_files, post_files table CRUD
- File/FileCreateDto <-> FileEntity 변환 (update는 존재하지 않는다)
- FileService: File 도메인 로직 (기본 crd)

해당 이슈에서는 이에 사용될 Dto 및 도메인/엔티티 클래스와 각 클래스를 연결하는 converter를 구현하는 것을 목적으로 한다.

## Todo

-   [ ] FileEntity
-   [ ] FileCreateDto
-   [ ] File: 파일에 대한 공통 속성들을 담고 있다.
-   [ ] UserProfileImage: user Id를 추가로 갖고 있다.
-   [ ] CarouselImage: sequence를 추가로 갖고 있다. 캐러셀에서의 순서를 나타낸다.
-   [ ] ImageTypes enum: default, front, rear로 나뉘며, 전/후면 동시에 제공 시 작은 화면이 front 배경이 rear에 해당한다.

## Check Priority

Expected Priority: CRITICAL

## Reference (Optional)
![image](https://github.com/user-attachments/assets/fa3bd99d-7fee-4c08-b363-ffc384791d97)
