### ISSUE TITLE
[FEAT] Other Domains

### ISSUE THREAD

**Issue by sueelly** [f-lab-edu/SnapNOW#11]
# Contents

남은 도메인 클래들을 구현한다.

## Description

Comment, UserElement, UserList, HashtagPosts, CommentEntity

## Todo

-   [ ] CommentEntity
-   [ ] CommentCreateDto
-   [ ] CommentUpdateDto
-   [ ] Comment: 기본 댓글 정보를 갖는다.
-   [ ] CommentElement: 댓글과 대댓글을 동시에 갖는다.
-   [ ] CommentList: CommentElement를 리스트로 갖는다.
-   [ ] CommentConverter
-   [ ] HashtagEntity
-   [ ] HashtagPosts
-   [ ] HashtagConverter
-   [ ] UserElement: follow / follwing 정보도 포함하는 user profile이다.
-   [ ] UserList: UserElement를 요소로 갖는 리스트를 포함한다.

## Check Priority

Expected Priority: HIGH

## Reference (Optional)

(null)
