### ISSUE TITLE
[FEAT] User mapper

### ISSUE THREAD

**Issue by sueelly** [f-lab-edu/SnapNOW#3]
# Contents

Mybatis를 사용하여 DB의 users, user_settings, user_infos table과의 매핑을 구현한다.

## Description

SNS에서 프로필로 공개되는 정보들로 자주 조회되고 수정되는 users table,
남들에게 공개되지 않는 개인 정보가 담겨 자주 조회되지 않는 user_infos table,
해당 유저가 설정한 설정값들이 저장되는 user_settings table
에 대한 값을 생성 / 수정 / 조회 / 삭제하는 Mapper를 구현한다.

## Todo

-   [ ] UserMapper class 구현
-   [ ] UserMapper.xml 구현
-   [ ] UserMapperTest 구현
-   [ ] UserInfoMapper class 구현
-   [ ] UserInfoMapper.xml 구현
-   [ ] UserInfoMapperTest 구현
-   [ ] UserSettingMapper class 구현
-   [ ] UserSettingMapper.xml 구현
-   [ ] UserSettingMapperTest 구현

## Check Priority

Expected Priority: HIGH

## Reference (Optional)

(null)
