### ISSUE TITLE
[FEAT] User Domain

### ISSUE THREAD

**Issue by sueelly** [f-lab-edu/SnapNOW#8]
# Contents

User Domain 클래스들을 구현한다.

## Description

User Domain 모듈에서 하는 일은 다음과 같다.
- user table CRUD
- User/UserCreateDto/UserUpdateDto <-> UserEntity 변환
- UserService: User 도메인 로직

해당 이슈에서는 이에 사용될 Dto 및 도메인/엔티티 클래스와 각 클래스를 연결하는 converter를 구현하는 것을 목적으로 한다.

이때 도메인 클래스는 application module에서 비즈니스 로직에 사용되고, 엔티티 클래스는 db의 컬럼들을 그대로 갖고 있어 도메인 로직에 활용되는 클래스이다.

## Todo

-   [x] UserSettingEntity: 유저의 설정값을 담은 정보이다. (user_settings)
-   [x] UserProfileEntity: 유저 프로필에 해당하는 정보이다. (users)
-   [x] UserAccountEntity: 유저의 private한 정보이다. (user_accounts)
-   [x] UserCreateDto: user profile, user account 정보를 갖고 있다.
-   [x] UserProfileUpdateDto
-   [x] UserAccountUpdateDto
-   [x] UserSettingUpdateDto
-   [x] UserProfile: 유저의 프로필 이미지, 계정 이름, 유저 이름, 설명을 갖고 있다. user을 조인하여 사용하는 곳에서 대부분 이 정보만 활용한다.
-   [x] UserSetting
-   [x] UserAccount
-   [ ] UserConverter

## Check Priority

Expected Priority: CRITICAL

## Reference (Optional)

(null)
